services:
    php:
        build:
            context: ./vendor/laravel/sail/runtimes/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.3/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '80:80'
            - '5173:5173'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - redis
            # - memcached
            - minio
            - mariadb
            - meilisearch
            - mailpit
            # - soketi
    redis:
        image: 'redis:alpine'
        ports:
            - '6379:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
    # memcached:
    #     image: 'memcached:alpine'
    #     ports:
    #         - '11211:11211'
    #     networks:
    #         - sail
    minio:
        image: 'minio/minio:latest'
        ports:
            - '9000:9000'
            - '8900:8900'
        environment:
            MINIO_ROOT_USER: sail
            MINIO_ROOT_PASSWORD: password
        volumes:
            - 'sail-minio:/data/minio'
        networks:
            - sail
        command: 'minio server /data/minio --console-address ":8900"'
    mariadb:
        image: 'mariadb:10'
        ports:
            - '3307:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sail-mariadb:/var/lib/mysql'
        networks:
            - sail
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        ports:
            - '7700:7700'
        environment:
            MEILI_NO_ANALYTICS: '${MEILISEARCH_NO_ANALYTICS:-false}'
        volumes:
            - 'sail-meilisearch:/meili_data'
        networks:
            - sail
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
    # soketi:
    #     image: 'quay.io/soketi/soketi:latest-16-alpine'
    #     environment:
    #         SOKETI_DEBUG: '${SOKETI_DEBUG:-1}'
    #         SOKETI_METRICS_SERVER_PORT: '9601'
    #         SOKETI_DEFAULT_APP_ID: '${PUSHER_APP_ID}'
    #         SOKETI_DEFAULT_APP_KEY: '${PUSHER_APP_KEY}'
    #         SOKETI_DEFAULT_APP_SECRET: '${PUSHER_APP_SECRET}'
    #     ports:
    #         - '${PUSHER_PORT:-6001}:6001'
    #         - '${PUSHER_METRICS_PORT:-9601}:9601'
    #     networks:
    #         - sail
    # elastic:
    #     image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    #     volumes:
    #         - 'sail-elasticsearch:/usr/share/elasticsearch/data'
    #     ports:
    #         - '9201:9200'
    #         - '9302:9300'
    #     environment:
    #         - discovery.type=single-node
    #         - ES_JAVA_OPTS=-Xms512m -Xmx512m
    #         - xpack.security.enabled=false
    #     networks:
    #         - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-redis:
        driver: local
    sail-minio:
        driver: local
    sail-mariadb:
        driver: local
    sail-meilisearch:
        driver: local
    # sail-elasticsearch:
    #     driver: local